# Generated by Django 3.2.10 on 2022-01-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={},
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='name',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='cast',
            field=models.CharField(default=0, help_text='Introduzca nombres separados por comas', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='place',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='rating',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='title',
            field=models.CharField(default=0, max_length=255, verbose_name='título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
