# Generated by Django 3.2.10 on 2022-02-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('blog', '0009_bloglistingpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogListingPage',
        ),
    ]
